1_1:
	python main.py start1.txt goal1.txt 1 sl.txt
1_2:
	python main.py start2.txt goal2.txt 1 sl.txt
1_3:
	python main.py start3.txt goal3.txt 1 sl.txt
2_1:
	python main.py start1.txt goal1.txt 2 sl.txt
2_2:
	python main.py start2.txt goal2.txt 2 sl.txt
2_3:
	python main.py start3.txt goal3.txt 2 sl.txt
3_1:
	python main.py start1.txt goal1.txt 3 sl.txt
3_2:
	python main.py start2.txt goal2.txt 3 sl.txt
3_3:
	python main.py start3.txt goal3.txt 3 sl.txt
4_1:
	python main.py start1.txt goal1.txt 4 sl.txt
4_2:
	python main.py start2.txt goal2.txt 4 sl.txt
4_3:
	python main.py start3.txt goal3.txt 4 sl.txt
