1_1:
	python main.py start1.txt goal1.txt bfs 1_1sl.txt
1_2:
	python main.py start2.txt goal2.txt bfs 1_2sl.txt
1_3:
	python main.py start3.txt goal3.txt bfs 1_3sl.txt
2_1:
	python main.py start1.txt goal1.txt dfs 2_1sl.txt
2_2:
	python main.py start2.txt goal2.txt dfs 2_2sl.txt
2_3:
	python main.py start3.txt goal3.txt dfs 2_3sl.txt
3_1:
	python main.py start1.txt goal1.txt iddfs 3_1sl.txt
3_2:
	python main.py start2.txt goal2.txt iddfs 3_2sl.txt
3_3:
	python main.py start3.txt goal3.txt iddfs 3_3sl.txt
4_1:
	python main.py start1.txt goal1.txt astar 4_1sl.txt
4_2:
	python main.py start2.txt goal2.txt astar 4_2sl.txt
4_3:
	python main.py start3.txt goal3.txt astar 4_3sl.txt
